### ISSUE TITLE
[Computability: Reducibility] Typo in Example 68

### ISSUE THREAD

**Issue by ajaypillay** [eecs376/issues#1]
## Current language
In Example 68, the last line of the decider $C$ states:
>$\textbf{Run } F \text{ on } x \text{ and answer as } F$

## Problem
$F$ should be run on $\langle M'\rangle$ instead since $F$ is the black box deciding $L_\text{FOO}$.

## Proposed language

Change
>$\textbf{Run } F \text{ on } x \text{ and answer as } F$

To
>$\textbf{Run } F \text{ on } \langle M'\rangle \text{ and answer as } F$

(credit: \@947 in Piazza for W22)

**Comment by amirkamil** [comment]
Fixed in commit [1721ec5](https://github.com/eecs376/notes/commit/1721ec5baec9d22beabe96da9d2679456e9e821c).
