### ISSUE TITLE
Typo in Example 48

### ISSUE THREAD

**Issue by ajaypillay** [eecs376/issues#10]
## Current language
Example 48 states:

> an arbitrary negative integer $i$ appears at position $2i$.

> Formally, we can define a one-to-one function $f:\mathbb{Z}\to\mathbb{N}$ as follows: 

$$
f(i) = \begin{cases}
    2i-1 & \text{if } i > 0 \\
    2i & \text{otherwise.}
\end{cases}
$$

## Problem
The position when $i$ is non-positive should be $|2i|$ or $2(-i)$.

## Proposed language

> an arbitrary non-positive integer $i$ appears at position $|2i|$.

> Formally, we can define a one-to-one function $f:\mathbb{Z}\to\mathbb{N}$ as follows: 

$$
f(i) = \begin{cases}
    2i-1 & \text{if } i > 0 \\
    |2i| & \text{otherwise.}
\end{cases}
$$

I think either $2(-i)$ or $|2i|$ work fine, though I think it's probably easier to parse if it's $|2i|$.

(credit: @606 in Piazza for W23)

**Comment by amirkamil** [comment]
Fixed by @cpeikert in [b7e6f5c](https://github.com/eecs376/notes/commit/b7e6f5c1788206a794c022da048ef18f0ca875b4).
