### ISSUE TITLE
[Computability: Recognizability] Typo before Exercise 76

### ISSUE THREAD

**Issue by ajaypillay** [eecs376/issues#2]
## Current language
In the second last paragraph right before Exercise 76, it states:
>... so $M$ is a recognizer for $B$. Since there exists a machine that decides $B$, $B$ is a recognizable language.

## Problem
It should state **_recognizes_** instead of **_decides_**.

## Proposed language

Change
>... so $M$ is a recognizer for $B$. Since there exists a machine that decides $B$, $B$ is a recognizable language.

To
>... so $M$ is a recognizer for $B$. Since there exists a machine that recognizes $B$, $B$ is a recognizable language.

(credit: @1184 in Piazza for W22)

**Comment by amirkamil** [comment]
Fixed in commit [1721ec5](https://github.com/eecs376/notes/commit/1721ec5baec9d22beabe96da9d2679456e9e821c).
