### ISSUE TITLE
Superset → Proper Superset

### ISSUE THREAD

**Issue by nvarner** [eecs376/issues#3]
Which unit?
**Computability/Turing Machines**

## Current language
> The main differences between finite automata and Turing machines are as follows:
> Behavior | Finite Automata | Turing Machines
> ---|---|---
> Tape alphabet a superset of input alphabet | No | Yes
> ... | ... | ...

## Problem
The tape alphabet for finite automata is exactly the input alphabet. Since every set is a superset of itself, the tape alphabet is actually a superset of the input alphabet. However, the idea behind this row is to say that the tape alphabet for a Turing machine can be bigger than its input alphabet, so I propose rephrasing to preserve that while removing the possibly confusing claim about finite automata.

## Proposed language

Change
> Tape alphabet a superset of input alphabet

To
> Tape alphabet may be a proper superset of input alphabet

**Comment by amirkamil** [comment]
Resolved. Thanks for finding this and reporting it!
